global using UnitsNet;
global using UnitsNet.Units;
global using VividOrange.Materials.StandardMaterials.En;
global using VividOrange.Profiles;
global using VividOrange.Sections;
global using VividOrange.Sections.Reinforcement;
global using VividOrange.Standards.Eurocode;
global using Xunit;
global using Strain = UnitsNet.Ratio;
global using StrainUnit = UnitsNet.Units.RatioUnit;
